;;; eshell-up-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eshell-up.el

(autoload 'eshell-up "eshell-up" "\
Go to a specific parent directory in eshell.
Argument MATCH a string that identifies the parent directory to go
to.

(fn &optional MATCH)" t)
(autoload 'eshell-up-peek "eshell-up" "\
Find a specific parent directory in eshell.
Argument MATCH a string that identifies the parent directory to find

(fn &optional MATCH)" t)
(register-definition-prefixes "eshell-up" '("eshell-up-"))

;;; End of scraped data

(provide 'eshell-up-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eshell-up-autoloads.el ends here
