;;; timu-caribbean-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from timu-caribbean-theme.el

(autoload 'timu-caribbean-toggle-flavour "timu-caribbean-theme" "\
Toggle between \"chillin\" and \"buzzin\" `timu-caribbean-flavour'." t)
(autoload 'timu-caribbean-toggle-mode-line-border "timu-caribbean-theme" "\
Toggle between borders and no borders for the `mode-line'.
Customize `timu-caribbean-mode-line-border' the to achieve this." t)
(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "timu-caribbean-theme" '("timu-caribbean"))

;;; End of scraped data

(provide 'timu-caribbean-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; timu-caribbean-theme-autoloads.el ends here
