;;; lsp-javacomp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from lsp-javacomp.el

(autoload 'lsp-javacomp-install-server "lsp-javacomp" "\
Download the JavaComp server JAR file if it does not exist.

If PROMPT-EXISTS is non-nil, show a message if the server jar
file already exists.

(fn &optional PROMPT-EXISTS)" t)
(autoload 'lsp-javacomp-update-server "lsp-javacomp" "\
Update JavaComp jar file to the latest version." t)
(register-definition-prefixes "lsp-javacomp" '("lsp-javacomp-"))

;;; End of scraped data

(provide 'lsp-javacomp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lsp-javacomp-autoloads.el ends here
