;;; zoxide-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from zoxide.el

(autoload 'zoxide-run "zoxide" "\
Run zoxide command with args.
The first argument ASYNC specifies whether calling asynchronously or not.
The second argument ARGS is passed to zoxide directly, like query -l

(fn ASYNC &rest ARGS)")
(autoload 'zoxide-add "zoxide" "\
Add PATH to zoxide database.  This function is called asynchronously.

Notice: `expand-file-name' is used on path here.  If your path aren't compatible
with it, a new wrapper with `zoxide-run' should be done manually.

(fn &optional PATH &rest _)" t)
(autoload 'zoxide-remove "zoxide" "\
Remove PATH from zoxide database.

Notice: `expand-file-name' is used on path here.  If your path aren't compatible
with it, a new wrapper with `zoxide-run' should be done manually.

(fn &optional PATH)" t)
(autoload 'zoxide-query-with "zoxide" "\
Search zoxide database with QUERY by calling zoxide query.
When calling interactively, it will open a buffer to show results.  Otherwise,
a list of paths is returned.

(fn QUERY)" t)
(autoload 'zoxide-query "zoxide" "\
Similar to `zoxide-query-with', but list all paths instead of matching." t)
(autoload 'zoxide-open-with "zoxide" "\
Search QUERY and run CALLBACK function with a selected path.

If NONINTERACTIVE is non-nil, the callback is always called
directly with the selected path as its first argument.

This is a help function to define interactive commands like
`zoxide-find-file'.  If you want to do things noninteractive, please use
`zoxide-query', filter results and pass it to your function manually instead.

(fn QUERY CALLBACK &optional NONINTERACTIVE)")
(autoload 'zoxide-find-file-with-query "zoxide" "\
Open file in path from zoxide with a search query." t)
(autoload 'zoxide-find-file "zoxide" "\
Open file in path from zoxide with all paths." t)
(autoload 'zoxide-cd-with-query "zoxide" "\
Select default directory through zoxide with a search query." t)
(autoload 'zoxide-cd "zoxide" "\
Select default directory through zoxide with all paths." t)
(autoload 'zoxide-travel "zoxide" "\
Like `zoxide-find-file', this function is used to open the path directly." t)
(autoload 'zoxide-travel-with-query "zoxide" "\
Like `zoxide-travel', a query mached at first." t)
(register-definition-prefixes "zoxide" '("zoxide-"))

;;; End of scraped data

(provide 'zoxide-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; zoxide-autoloads.el ends here
