;;; altcaps-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from altcaps.el

(autoload 'altcaps-word "altcaps" "\
Convert word to alternating letter casing.

With optional NUM as a numeric prefix argument, operate on NUM
words forward, defaulting to 1.  If NUM is negative, do so
backward.

Alternating letter casing denotes sarcasm or mockery.

(fn &optional NUM)" t)
(autoload 'altcaps-region "altcaps" "\
Convert region words between BEG and END to alternating case.
BEG and END are buffer positions.  When called interactively,
these are automatically determined as the active region's
boundaries, else the space between `mark' and `point'.

Alternating letter casing denotes sarcasm or mockery.

(fn BEG END)" t)
(autoload 'altcaps-dwim "altcaps" "\
Convert to alternating letter casing Do-What-I-Mean style.
With an active region, call `altcaps-region'.  Else
invoke `altcaps-word' with optional NUM, per that
command's functionality (read its doc string).

Alternating letter casing denotes sarcasm or mockery.

(fn &optional NUM)" t)
(register-definition-prefixes "altcaps" '("altcaps-"))

;;; End of scraped data

(provide 'altcaps-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; altcaps-autoloads.el ends here
