;;; hippo-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from hippo-themes.el

(add-to-list 'custom-theme-load-path (if load-file-name (file-name-directory load-file-name) default-directory))


;;; Generated autoloads from hippo-themes-light-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "hippo-themes-light-theme" '("hippo-themes-light"))


;;; Generated autoloads from hippo-themes-night-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "hippo-themes-night-theme" '("hippo-themes-night"))


;;; Generated autoloads from hippo-themes-paper-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "hippo-themes-paper-theme" '("hippo-themes-paper"))

;;; End of scraped data

(provide 'hippo-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; hippo-themes-autoloads.el ends here
