;;; shift-number-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from shift-number.el

(autoload 'shift-number-up "shift-number" "\
Increase the number at point (or on the current line) by ARG.

(fn &optional ARG)" t)
(autoload 'shift-number-down "shift-number" "\
Decrease the number at point (or on the current line) by ARG.

(fn &optional ARG)" t)
(register-definition-prefixes "shift-number" '("shift-number-"))

;;; End of scraped data

(provide 'shift-number-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; shift-number-autoloads.el ends here
