;;; moe-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from moe-dark-theme.el

(register-definition-prefixes "moe-dark-theme" '("moe-dark"))


;;; Generated autoloads from moe-light-theme.el

(register-definition-prefixes "moe-light-theme" '("moe-light"))


;;; Generated autoloads from moe-theme.el

(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "moe-theme" '("moe-"))


;;; Generated autoloads from moe-theme-flavours.el

(register-definition-prefixes "moe-theme-flavours" '("moe-theme-"))


;;; Generated autoloads from moe-theme-switcher.el

(register-definition-prefixes "moe-theme-switcher" '("convert-time-format-of-sunrise-and-sunset" "get-sunrise-sunset-string" "moe-" "switch-"))

;;; End of scraped data

(provide 'moe-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; moe-theme-autoloads.el ends here
