;;; moe-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from moe-dark-theme.el

(register-definition-prefixes "moe-dark-theme" '("moe-dark"))


;;; Generated autoloads from moe-light-theme.el

(register-definition-prefixes "moe-light-theme" '("moe-light"))


;;; Generated autoloads from moe-theme.el

(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "moe-theme" '("moe-"))


;;; Generated autoloads from moe-theme-flavours.el

(register-definition-prefixes "moe-theme-flavours" '("moe-theme-"))


;;; Generated autoloads from moe-theme-switcher.el

(defvar moe-theme-switcher-mode nil "\
Non-nil if Moe-Theme-Switcher mode is enabled.
See the `moe-theme-switcher-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `moe-theme-switcher-mode'.")
(custom-autoload 'moe-theme-switcher-mode "moe-theme-switcher" nil)
(autoload 'moe-theme-switcher-mode "moe-theme-switcher" "\
Minor mode for enabling automatic switching between the

`moe-light' and `moe-dark' themes accoring to the time of day.

See the documentation for `moe-theme-switcher-enable' and
`moe-theme-switch-by-sunrise-and-sunset' for details.

This is a global minor mode.  If called interactively, toggle the
`Moe-Theme-Switcher mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='moe-theme-switcher-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "moe-theme-switcher" '("moe-theme-switch"))

;;; End of scraped data

(provide 'moe-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; moe-theme-autoloads.el ends here
