;;; substitute-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from substitute.el

 (autoload 'substitute-target-in-buffer "substitute")
 (autoload 'substitute-target-in-defun "substitute")
 (autoload 'substitute-target-below-point "substitute")
 (autoload 'substitute-target-above-point "substitute")
 (autoload 'substitute-prefix-map "substitute")
(register-definition-prefixes "substitute" '("substitute-"))

;;; End of scraped data

(provide 'substitute-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; substitute-autoloads.el ends here
